version: '3'

# Ports:
#   - Application Services: 80xx
#   - Databases:            81xx
#   - Dashboards:           82xx

services:
  proxy:
    depends_on:
      - api
      - application
      - authentication
      - noflo
    links:
      - api
      - application
      - authentication
      - noflo
    build: ./services/proxy
    ports:
      - 8000:8000
    environment:
      - API_HOST=api
      - API_PORT=8002
      - APPLICATION_HOST=application
      - APPLICATION_PORT=8001
      - AUTHENTICATION_HOST=authentication
      - AUTHENTICATION_PORT=8003
      - NODE_ENV=develop
      - NOFLO_HOST=noflo
      - NOFLO_PORT=8003
      - PROXY_HOST=proxy
      - PROXY_PORT=8000
      - REDIS_COMMANDER_HOST=redis-commander
      - REDIS_COMMANDER_PORT=8202
      - REDIS_HOST=redis
      - REDIS_PORT=8100
      - RETHINKDB_CHATEAU_HOST=rethinkdb-chateau
      - RETHINKDB_CHATEAU_PORT=8201
      - RETHINKDB_DB=tomwielandnl_develop
      - RETHINKDB_HOST=rethinkdb
      - RETHINKDB_PORT=8102
      - SERVICE_SECRET=keyboardcat

  application:
    build: ./services/application
    ports:
      - 8001:8001
    volumes:
      - ./services/application:/service
    environment:
      - API_HOST=api
      - API_PORT=8002
      - APPLICATION_HOST=application
      - APPLICATION_PORT=8001
      - AUTHENTICATION_HOST=authentication
      - AUTHENTICATION_PORT=8003
      - NODE_ENV=develop
      - NOFLO_HOST=noflo
      - NOFLO_PORT=8003
      - PROXY_HOST=proxy
      - PROXY_PORT=8000
      - REDIS_COMMANDER_HOST=redis-commander
      - REDIS_COMMANDER_PORT=8202
      - REDIS_HOST=redis
      - REDIS_PORT=8100
      - RETHINKDB_CHATEAU_HOST=rethinkdb-chateau
      - RETHINKDB_CHATEAU_PORT=8201
      - RETHINKDB_DB=tomwielandnl_develop
      - RETHINKDB_HOST=rethinkdb
      - RETHINKDB_PORT=8102
      - SERVICE_SECRET=keyboardcat

  api:
    build: ./services/api
    ports:
      - 8002:8002
    volumes:
      - ./services/api:/service
    environment:
      - API_HOST=api
      - API_PORT=8002
      - APPLICATION_HOST=application
      - APPLICATION_PORT=8001
      - AUTHENTICATION_HOST=authentication
      - AUTHENTICATION_PORT=8003
      - NODE_ENV=develop
      - NOFLO_HOST=noflo
      - NOFLO_PORT=8003
      - PROXY_HOST=proxy
      - PROXY_PORT=8000
      - REDIS_COMMANDER_HOST=redis-commander
      - REDIS_COMMANDER_PORT=8202
      - REDIS_HOST=redis
      - REDIS_PORT=8100
      - RETHINKDB_CHATEAU_HOST=rethinkdb-chateau
      - RETHINKDB_CHATEAU_PORT=8201
      - RETHINKDB_DB=tomwielandnl_develop
      - RETHINKDB_HOST=rethinkdb
      - RETHINKDB_PORT=8102
      - SERVICE_SECRET=keyboardcat

  authentication:
    build: ./services/authentication
    ports:
      - 8003:8003
    volumes:
      - ./services/authentication:/service
    environment:
      - API_HOST=api
      - API_PORT=8002
      - APPLICATION_HOST=application
      - APPLICATION_PORT=8001
      - AUTHENTICATION_HOST=authentication
      - AUTHENTICATION_PORT=8003
      - NODE_ENV=develop
      - NOFLO_HOST=noflo
      - NOFLO_PORT=8003
      - PROXY_HOST=proxy
      - PROXY_PORT=8000
      - REDIS_COMMANDER_HOST=redis-commander
      - REDIS_COMMANDER_PORT=8202
      - REDIS_HOST=redis
      - REDIS_PORT=8100
      - RETHINKDB_CHATEAU_HOST=rethinkdb-chateau
      - RETHINKDB_CHATEAU_PORT=8201
      - RETHINKDB_DB=tomwielandnl_develop
      - RETHINKDB_HOST=rethinkdb
      - RETHINKDB_PORT=8102
      - SERVICE_SECRET=keyboardcat

  noflo:
    build: ./services/noflo
    ports:
      - 8004:8004
    volumes:
      - ./services/noflo:/service
    environment:
      - API_HOST=api
      - API_PORT=8002
      - APPLICATION_HOST=application
      - APPLICATION_PORT=8001
      - AUTHENTICATION_HOST=authentication
      - AUTHENTICATION_PORT=8003
      - NODE_ENV=develop
      - NOFLO_HOST=noflo
      - NOFLO_PORT=8003
      - PROXY_HOST=proxy
      - PROXY_PORT=8000
      - REDIS_COMMANDER_HOST=redis-commander
      - REDIS_COMMANDER_PORT=8202
      - REDIS_HOST=redis
      - REDIS_PORT=8100
      - RETHINKDB_CHATEAU_HOST=rethinkdb-chateau
      - RETHINKDB_CHATEAU_PORT=8201
      - RETHINKDB_DB=tomwielandnl_develop
      - RETHINKDB_HOST=rethinkdb
      - RETHINKDB_PORT=8102
      - SERVICE_SECRET=keyboardcat

  redis:
    image: redis:latest
    ports:
      - 8100:8100
    volumes:
      - ./services/redis/data:/data
    command: "redis-server --port 8100"
    environment:
      - API_HOST=api
      - API_PORT=8002
      - APPLICATION_HOST=application
      - APPLICATION_PORT=8001
      - AUTHENTICATION_HOST=authentication
      - AUTHENTICATION_PORT=8003
      - NODE_ENV=develop
      - NOFLO_HOST=noflo
      - NOFLO_PORT=8003
      - PROXY_HOST=proxy
      - PROXY_PORT=8000
      - REDIS_COMMANDER_HOST=redis-commander
      - REDIS_COMMANDER_PORT=8202
      - REDIS_HOST=redis
      - REDIS_PORT=8100
      - RETHINKDB_CHATEAU_HOST=rethinkdb-chateau
      - RETHINKDB_CHATEAU_PORT=8201
      - RETHINKDB_DB=tomwielandnl_develop
      - RETHINKDB_HOST=rethinkdb
      - RETHINKDB_PORT=8102
      - SERVICE_SECRET=keyboardcat

  redis-commander:
    build: ./services/redis-commander
    depends_on:
      - redis
    links:
      - redis
    ports:
      - 8202:8202
    command: "redis-commander --redis-host redis --redis-port 8100 --port 8202 --address 0.0.0.0"
    environment:
      - API_HOST=api
      - API_PORT=8002
      - APPLICATION_HOST=application
      - APPLICATION_PORT=8001
      - AUTHENTICATION_HOST=authentication
      - AUTHENTICATION_PORT=8003
      - NODE_ENV=develop
      - NOFLO_HOST=noflo
      - NOFLO_PORT=8003
      - PROXY_HOST=proxy
      - PROXY_PORT=8000
      - REDIS_COMMANDER_HOST=redis-commander
      - REDIS_COMMANDER_PORT=8202
      - REDIS_HOST=redis
      - REDIS_PORT=8100
      - RETHINKDB_CHATEAU_HOST=rethinkdb-chateau
      - RETHINKDB_CHATEAU_PORT=8201
      - RETHINKDB_DB=tomwielandnl_develop
      - RETHINKDB_HOST=rethinkdb
      - RETHINKDB_PORT=8102
      - SERVICE_SECRET=keyboardcat

  rethinkdb:
    build: ./services/rethinkdb
    ports:
      - 8102:8102 # 28015
      - 8103:8103 # 29015
      - 8200:8200 # 8080
    volumes:
      - ./services/rethinkdb/data:/data
    environment:
      - API_HOST=api
      - API_PORT=8002
      - APPLICATION_HOST=application
      - APPLICATION_PORT=8001
      - AUTHENTICATION_HOST=authentication
      - AUTHENTICATION_PORT=8003
      - NODE_ENV=develop
      - NOFLO_HOST=noflo
      - NOFLO_PORT=8003
      - PROXY_HOST=proxy
      - PROXY_PORT=8000
      - REDIS_COMMANDER_HOST=redis-commander
      - REDIS_COMMANDER_PORT=8202
      - REDIS_HOST=redis
      - REDIS_PORT=8100
      - RETHINKDB_CHATEAU_HOST=rethinkdb-chateau
      - RETHINKDB_CHATEAU_PORT=8201
      - RETHINKDB_DB=tomwielandnl_develop
      - RETHINKDB_HOST=rethinkdb
      - RETHINKDB_PORT=8102
      - SERVICE_SECRET=keyboardcat

  rethinkdb-chateau:
    build: ./services/rethinkdb-chateau
    depends_on:
      - rethinkdb
    links:
      - rethinkdb
    ports:
      - 8201:8201
    environment:
      - API_HOST=api
      - API_PORT=8002
      - APPLICATION_HOST=application
      - APPLICATION_PORT=8001
      - AUTHENTICATION_HOST=authentication
      - AUTHENTICATION_PORT=8003
      - NODE_ENV=develop
      - NOFLO_HOST=noflo
      - NOFLO_PORT=8003
      - PROXY_HOST=proxy
      - PROXY_PORT=8000
      - REDIS_COMMANDER_HOST=redis-commander
      - REDIS_COMMANDER_PORT=8202
      - REDIS_HOST=redis
      - REDIS_PORT=8100
      - RETHINKDB_CHATEAU_HOST=rethinkdb-chateau
      - RETHINKDB_CHATEAU_PORT=8201
      - RETHINKDB_DB=tomwielandnl_develop
      - RETHINKDB_HOST=rethinkdb
      - RETHINKDB_PORT=8102
      - SERVICE_SECRET=keyboardcat
