version: '3'

services:
  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data

  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test_nextjs_user
      - POSTGRES_PASSWORD=test_nextjs_password
      - POSTGRES_DB=test_nextjs_develop
    volumes:
      - ./db:/var/lib/postgresql

  redis-commander:
    depends_on:
      - redis
    links:
      - redis
    restart: always
    build: ./redis-commander
    ports:
      - 4001:3000
    command: "redis-commander --redis-host redis --redis-port 6379 --port 3000 --address 0.0.0.0"

  proxy:
    links:
      - app
      - api
    build: ./proxy
    ports:
      - 3000:80
    environment:
      - APP_REMOTE=http://app:3001
      - API_REMOTE=http://api:3002

  app:
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    build: ./app
    ports:
      - 3001:3001
    volumes:
      - ./app:/service
    environment:
      - NODE_ENV=develop
      - APP_HOST=0.0.0.0
      - APP_PORT=3001
      - APP_KEYS=keyboardkat
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_HOST=api
      - API_PORT=3002
      - API_PATH=api
    command: "yarn run dev"

  api:
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    build: ./api
    ports:
      - 3002:3002
    volumes:
      - ./api:/service
    environment:
      - NODE_ENV=develop
      - APP_HOST=0.0.0.0
      - APP_PORT=3002
      - APP_KEYS=keyboardkat
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=test_nextjs_user
      - DB_PASS=test_nextjs_password
      - DB_NAME=test_nextjs_develop
    command: "yarn run dev"

  # sessions:
  #   depends_on:
  #     - redis
  #   links:
  #     - redis
  #   restart: always
  #   build: ./sessions
  #   ports:
  #     - 3003:3000
  #   environment:
  #     - RS_PORT=3000
  #     - RS_REDISHOST=redis
  #     - RS_REDISPORT=6379
  #     - RS_NAMESPACE=rs
  #     - RS_LOGLEVEL=info
