version: '3'

# Ports:
#   - Application Services: 80xx
#   - Databases:            81xx
#   - Dashboards:           82xx

services:
  proxy:
    build: ./services/proxy
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}
    volumes:
      - ./services/proxy:/service
    env_file: .env

  web:
    build: ./services/web
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    volumes:
      - ./services/web:/service
    env_file: .env

  api:
    build: ./services/api
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./services/api:/service
    env_file: .env

  authentication:
    build: ./services/authentication
    ports:
      - ${AUTHENTICATION_PORT}:${AUTHENTICATION_PORT}
    volumes:
      - ./services/authentication:/service
    env_file: .env

  redis:
    build: ./services/redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./services/redis:/service
      - ./services/redis/data:/data
    env_file: .env

  redis-admin:
    build: ./services/redis-admin
    ports:
      - ${REDIS_ADMIN_PORT}:${REDIS_ADMIN_PORT}
    volumes:
      - ./services/redis-admin:/service
    env_file: .env

  postgresql:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./services/postgresql/data:/var/lib/postgresql/data
    env_file: .env

  postgresql-admin:
    image: sosedoff/pgweb
    links:
      - postgresql
    depends_on:
      - postgresql
    ports: 
      - ${POSTGRES_ADMIN_PORT}:${POSTGRES_ADMIN_PORT}
    env_file: .env

  influxdb:
    image: influxdb:latest
    ports:
      - ${INFLUXDB_PORT}:${INFLUXDB_PORT}
    volumes:
      - ./services/influxdb/data:/var/lib/influxdb
    env_file: .env

  influxdb-chronograf:
    image: chronograf:latest
    ports:
      - ${INFLUXDB_CHRONOGRAF_PORT}:${INFLUXDB_CHRONOGRAF_PORT}
    volumes:
      - ./services/influxdb-chronograf/data:/var/lib/chronograf
    env_file: .env

  influxdb-telegraf:
    image: telegraf:latest
    ports:
      - ${INFLUXDB_TELEGRAF_STATSD_PORT}:${INFLUXDB_TELEGRAF_STATSD_PORT}
      - ${INFLUXDB_TELEGRAF_UDP_PORT}:${INFLUXDB_TELEGRAF_UDP_PORT}
      - ${INFLUXDB_TELEGRAF_TCP_PORT}:${INFLUXDB_TELEGRAF_TCP_PORT}
    volumes:
      - ./services/influxdb-telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file: .env

  influxdb-kapacitor:
    image: kapacitor:latest
    ports:
      - ${INFLUXDB_KAPACITOR_PORT}:${INFLUXDB_KAPACITOR_PORT}
    volumes:
      - ./services/influxdb-kapacitor/data:/var/lib/kapacitor
    env_file: .env

  # noflo:
  #   build: ./services/noflo
  #   ports:
  #     - ${NOFLO_PORT}:${NOFLO_PORT}
  #   volumes:
  #     - ./services/noflo:/service
  #   env_file: .env

  # arangodb:
  #   image: arangodb
  #   ports:
  #     - ${ARANGO_PORT}:${ARANGO_PORT}
  #   volumes:
  #     - ./services/arangodb/data:/var/lib/arangodb3
  #     - ./services/arangodb/apps:/var/lib/arangodb3-apps
  #   env_file: .env

  # eventstore:
  #   image: eventstore/eventstore
  #   ports:
  #     - ${EVENTSTORE_PORT}:${EVENTSTORE_PORT}
  #     - ${EVENTSTORE_HTTP_PORT}:${EVENTSTORE_HTTP_PORT}
  #   volumes:
  #     - ./services/eventstore/data:/var/lib/eventstore
  #     - ./services/eventstore/logs:/var/log/eventstore


  # rethinkdb:
  #   build: ./services/rethinkdb
  #   ports:
  #     - ${RETHINKDB_PORT}:${RETHINKDB_PORT}
  #     - ${RETHINKDB_PORT_INTRACLUSTER}:${RETHINKDB_PORT_INTRACLUSTER}
  #     - ${RETHINKDB_PORT_WEB}:${RETHINKDB_PORT_WEB}
  #   volumes:
  #     - ./services/rethinkdb/data:/data
  #   env_file: .env

  # rethinkdb-chateau:
  #   build: ./services/rethinkdb-chateau
  #   ports:
  #     - ${RETHINKDB_CHATEAU_PORT}:${RETHINKDB_CHATEAU_PORT}
  #   volumes:
  #     - ./services/rethinkdb-chateau:/service
  #   env_file: .env
