version: '3'

# Ports:
#   - Application Services: 80xx
#   - Databases:            81xx
#   - Dashboards:           82xx

services:
  proxy:
    depends_on:
      - api
      - application
      - authentication
      - noflo
    links:
      - api
      - application
      - authentication
      - noflo
    build: ./services/proxy
    ports:
      - 8000:8000
    env_file: ./lib/service-docker.env

  application:
    build: ./services/application
    ports:
      - 8001:8001
    volumes:
      - ./services/application:/service
    env_file: ./lib/service-docker.env

  api:
    build: ./services/api
    ports:
      - 8002:8002
    volumes:
      - ./services/api:/service
    env_file: ./lib/service-docker.env

  authentication:
    build: ./services/authentication
    ports:
      - 8003:8003
    volumes:
      - ./services/authentication:/service
    env_file: ./lib/service-docker.env

  noflo:
    build: ./services/noflo
    ports:
      - 8004:8004
    volumes:
      - ./services/noflo:/service
    env_file: ./lib/service-docker.env

  redis:
    image: redis:latest
    ports:
      - 8100:8100
    volumes:
      - ./services/redis/data:/data
    command: "redis-server --port 8100"
    env_file: ./lib/service-docker.env

  redis-commander:
    build: ./services/redis-commander
    depends_on:
      - redis
    links:
      - redis
    ports:
      - 8202:8202
    command: "redis-commander --redis-host redis --redis-port 8100 --port 8202 --address 0.0.0.0"
    env_file: ./lib/service-docker.env

  rethinkdb:
    build: ./services/rethinkdb
    ports:
      - 8102:8102 # 28015
      - 8103:8103 # 29015
      - 8200:8200 # 8080
    volumes:
      - ./services/rethinkdb/data:/data
    env_file: ./lib/service-docker.env

  rethinkdb-chateau:
    build: ./services/rethinkdb-chateau
    depends_on:
      - rethinkdb
    links:
      - rethinkdb
    ports:
      - 8201:8201
    env_file: ./lib/service-docker.env
