version: '3'
services:
  proxy:
    image: traefik
    command: '-c /dev/null --api --docker --docker.domain=docker.localhost --logLevel=DEBUG'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './services/proxy/traefik.toml:/traefik.toml'
      - './services/proxy/acme.json:/acme.json'

  postgresql:
    image: 'postgres:latest'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - './services/postgresql/data:/var/lib/postgresql/data'
    env_file: .env

  postgresql-admin:
    image: sosedoff/pgweb
    depends_on:
      - postgresql
    ports:
      - '${POSTGRES_ADMIN_PORT}:${POSTGRES_ADMIN_PORT}'
    env_file: .env
    environment:
      - SERVICE_NAME=postgresql-admin
      - 'SERVICE_EXPOSE_PORT=${POSTGRES_ADMIN_PORT}'
    labels:
      - 'traefik.frontend.rule=Host:postgresql-admin.docker.localhost'
      - traefik.backend=postgresql-admin
      - 'traefik.port=${POSTGRES_ADMIN_PORT}'

  graphql:
    image: prismagraphql/prisma:1.14
    ports:
    - '${GRAPHQL_PORT}:${GRAPHQL_PORT}'
    environment:
      PRISMA_CONFIG: |
        port: ${GRAPHQL_PORT}
        # uncomment the next line and provide the env var
        # PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ${POSTGRES_HOST}
            port: ${POSTGRES_PORT}
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
            migrations: true
    labels:
      - 'traefik.frontend.rule=Host:graphql.docker.localhost'
      - traefik.backend=graphql
      - 'traefik.port=${GRAPHQL_PORT}'

  web:
    build: services/web
    ports:
      - '${WEB_PORT}:${WEB_PORT}'
      - '${WEB_HMR_PORT}:${WEB_HMR_PORT}'
    volumes:
      - './services/web:/service'
    env_file: .env
    labels:
      - 'traefik.frontend.rule=Host:docker.localhost'
      - traefik.backend=web
      - 'traefik.port=${WEB_PORT}'
