version: '3'

# Ports:
#   - Application Services: 80xx
#   - Databases:            81xx
#   - Dashboards:           82xx

services:
  proxy:
    build: ./services/proxy
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}
    volumes:
      - ./services/proxy:/service
      #- ./common:/service/common
    env_file: .env

  web:
    build: ./services/web
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    volumes:
      - ./services/web:/service
      #- ./common:/service/common
    env_file: .env

  api:
    build: ./services/api
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./services/api:/service
      #- ./common:/service/common
    env_file: .env

  authentication:
    build: ./services/authentication
    ports:
      - ${AUTHENTICATION_PORT}:${AUTHENTICATION_PORT}
    volumes:
      - ./services/authentication:/service
      #- ./common:/service/common
    env_file: .env

  redis:
    build: ./services/redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./services/redis:/service
      - ./services/redis/data:/data
      #- ./common:/service/common
    env_file: .env

  redis-commander:
    build: ./services/redis-commander
    ports:
      - ${REDIS_COMMANDER_PORT}:${REDIS_COMMANDER_PORT}
    volumes:
      - ./services/redis-commander:/service
      #- ./common:/service/common
    env_file: .env

  postgresql:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./services/postgresql/data:/var/lib/postgresql/data
      #- ./common:/service/common
    env_file: .env

  influxdb:
    image: influxdb:latest
    ports:
      - ${INFLUXDB_PORT}:${INFLUXDB_PORT_IN}
      - ${INFLUXDB_ADMIN_PORT}:${INFLUXDB_ADMIN_PORT_IN}
      - ${INFLUXDB_GRAPHITE_PORT}:${INFLUXDB_GRAPHITE_PORT_IN}
    volumes:
      - ./services/influxdb/data:/var/lib/influxdb
      #- ./common:/service/common
    env_file: .env


  # adminer:
  #   image: adminer
  #   ports:
  #     - ${POSTGRES_ADMIN_PORT}:${POSTGRES_ADMIN_PORT}

  # eventstore:
  #   image: eventstore/eventstore
  #   ports:
  #     - ${EVENTSTORE_PORT}:${EVENTSTORE_PORT}
  #     - ${EVENTSTORE_HTTP_PORT}:${EVENTSTORE_HTTP_PORT}
  #   volumes:
  #     - ./services/eventstore/data:/var/lib/eventstore
  #     - ./services/eventstore/logs:/var/log/eventstore

  # noflo:
  #   build: ./services/noflo
  #   ports:
  #     - ${NOFLO_PORT}:${NOFLO_PORT}
  #   volumes:
  #     - ./services/noflo:/service
  #     - ./common:/service/common
  #   env_file: .env

  # rethinkdb:
  #   build: ./services/rethinkdb
  #   ports:
  #     - ${RETHINKDB_PORT}:${RETHINKDB_PORT}
  #     - ${RETHINKDB_PORT_INTRACLUSTER}:${RETHINKDB_PORT_INTRACLUSTER}
  #     - ${RETHINKDB_PORT_WEB}:${RETHINKDB_PORT_WEB}
  #   volumes:
  #     - ./services/rethinkdb/data:/data
  #   env_file: .env

  # rethinkdb-chateau:
  #   build: ./services/rethinkdb-chateau
  #   ports:
  #     - ${RETHINKDB_CHATEAU_PORT}:${RETHINKDB_CHATEAU_PORT}
  #   volumes:
  #     - ./services/rethinkdb-chateau:/service
  #   env_file: .env
