version: '3'

# Ports:
#   - Application Services: 80xx
#   - Databases:            81xx
#   - Dashboards:           82xx

services:
  proxy:
    depends_on:
      - api
      - application
      - authentication
      - rethinkdb
      - redis
      # - noflo
    links:
      - api
      - application
      - authentication
      - rethinkdb
      - redis
      # - noflo
    build: ./services/proxy
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}
    volumes:
      - ./services/proxy:/service
    env_file: .env

  application:
    build: ./services/application
    depends_on:
      - rethinkdb
    links:
      - rethinkdb
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    volumes:
      - ./services/application:/service
    env_file: .env

  api:
    build: ./services/api
    depends_on:
      - rethinkdb
    links:
      - rethinkdb
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./services/api:/service
    env_file: .env

  authentication:
    build: ./services/authentication
    depends_on:
      - redis
      - rethinkdb
    links:
      - redis
      - rethinkdb
    ports:
      - ${AUTHENTICATION_PORT}:${AUTHENTICATION_PORT}
    volumes:
      - ./services/authentication:/service
    env_file: .env

  # noflo:
  #   build: ./services/noflo
  #   ports:
  #     - ${NOFLO_PORT}:${NOFLO_PORT}
  #   volumes:
  #     - ./services/noflo:/service
  #   env_file: .env

  redis:
    build: ./services/redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./services/redis:/service
    env_file: .env

  redis-commander:
    build: ./services/redis-commander
    depends_on:
      - redis
    links:
      - redis
    ports:
      - ${REDIS_COMMANDER_PORT}:${REDIS_COMMANDER_PORT}
    volumes:
      - ./services/redis-commander:/service
    env_file: .env

  rethinkdb:
    build: ./services/rethinkdb
    ports:
      - ${RETHINKDB_PORT}:${RETHINKDB_PORT}
      - ${RETHINKDB_PORT_INTRACLUSTER}:${RETHINKDB_PORT_INTRACLUSTER}
      - ${RETHINKDB_PORT_WEB}:${RETHINKDB_PORT_WEB}
    volumes:
      - ./services/rethinkdb/data:/data
    env_file: .env

  rethinkdb-chateau:
    build: ./services/rethinkdb-chateau
    depends_on:
      - rethinkdb
    links:
      - rethinkdb
    ports:
      - ${RETHINKDB_CHATEAU_PORT}:${RETHINKDB_CHATEAU_PORT}
    volumes:
      - ./services/rethinkdb-chateau:/service
    env_file: .env
