version: '3'

services:
  app:
    container_name: app
    build: ./app
    command: "npm run dev"
    expose:
      - 3000
    volumes:
      - ./app:/service
      - /node_modules
    environment:
      - PORT=3000
