version: '3'

# Ports:
#   - Application Services: 80xx
#   - Databases:            81xx
#   - Dashboards:           82xx

services:
  nats:
    image: nats:latest
    ports:
      - ${NATS_PORT}:${NATS_PORT}
      - ${NATS_HTTP_PORT}:${NATS_HTTP_PORT}
      - ${NATS_CLUSTER_PORT}:${NATS_CLUSTER_PORT}
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${NATS_HOST}:${NATS_HTTP_PORT}"]
      interval: 1m
      timeout: 10s
      retries: 3
      # start_period: 1m

  nats-admin:
    build: ./services/nats-admin
    ports:
      - ${NATS_ADMIN_PORT}:3000
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${NATS_ADMIN_HOST}:${NATS_ADMIN_PORT}"]
      interval: 1m
      timeout: 10s
      retries: 3
      # start_period: 1m

  redis:
    build: ./services/redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./services/redis:/service
      - ./services/redis/data:/data
    env_file: .env

  redis-admin:
    build: ./services/redis-admin
    depends_on:
      - redis
    ports:
      - ${REDIS_ADMIN_PORT}:${REDIS_ADMIN_PORT}
    volumes:
      - ./services/redis-admin:/service
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${REDIS_ADMIN_HOST}:${REDIS_ADMIN_PORT}"]
      interval: 1m
      timeout: 10s
      retries: 3
      # start_period: 1m

  postgresql:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./services/postgresql/data:/var/lib/postgresql/data
    env_file: .env

  postgresql-admin:
    image: sosedoff/pgweb
    depends_on:
      - postgresql
    links:
      - postgresql
    depends_on:
      - postgresql
    ports: 
      - ${POSTGRES_ADMIN_PORT}:${POSTGRES_ADMIN_PORT}
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${POSTGRES_HOST}:${POSTGRES_ADMIN_PORT}"]
      interval: 1m
      timeout: 10s
      retries: 3
      # start_period: 1m

  eventstore:
    image: eventstore/eventstore
    ports:
      - ${EVENTSTORE_PORT}:${EVENTSTORE_PORT}
      - ${EVENTSTORE_HTTP_PORT}:${EVENTSTORE_HTTP_PORT}
    volumes:
      - ./services/eventstore/data:/var/lib/eventstore
      - ./services/eventstore/logs:/var/log/eventstore
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${EVENTSTORE_HOST}:${EVENTSTORE_HTTP_PORT}"]
      interval: 1m
      timeout: 10s
      retries: 3
      # start_period: 1m

  proxy:
    build: ./services/proxy
    depends_on:
      - nats
      - redis
      - postgresql
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}
    volumes:
      - ./services/proxy:/service
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${PROXY_HOST}:${PROXY_PORT}"]
      interval: 1m
      timeout: 10s
      retries: 3
      # start_period: 1m

  authentication:
    build: ./services/authentication
    depends_on:
      - nats
      - proxy
      - redis
      - postgresql
    ports:
      - ${AUTHENTICATION_PORT}:${AUTHENTICATION_PORT}
    volumes:
      - ./services/authentication:/service
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${AUTHENTICATION_HOST}:${AUTHENTICATION_PORT}"]
      interval: 1m
      timeout: 10s
      retries: 3
      # start_period: 1m

  web:
    build: ./services/web
    depends_on:
      - nats
      - proxy
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    volumes:
      - ./services/web:/service
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${WEB_HOST}:${WEB_PORT}"]
      interval: 1m
      timeout: 10s
      retries: 3
      # start_period: 1m

  graphql:
    build: ./services/api
    depends_on:
      - nats
      - proxy
    ports:
      - ${API_GRAPHQL_PORT}:${API_GRAPHQL_PORT}
    volumes:
      - ./services/api:/service
    env_file: .env
    environment:
      - API_SERVICE_NAME=graphql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${API_GRAPHQL_HOST}:${API_GRAPHQL_PORT}"]
      interval: 1m
      timeout: 10s
      retries: 3
      # start_period: 1m

  orderbook-importer:
    build: ./services/api
    depends_on:
      - nats
    volumes:
      - ./services/api:/service
    env_file: .env
    environment:
      - API_SERVICE_NAME=orderbook-importer

  orderbook-state:
    build: ./services/api
    depends_on:
      - nats
    ports:
      - ${API_ORDERBOOK_STATE_PORT}:${API_ORDERBOOK_STATE_PORT}
    volumes:
      - ./services/api:/service
    env_file: .env
    environment:
      - API_SERVICE_NAME=orderbook-state

  # influxdb:
  #   image: influxdb:latest
  #   ports:
  #     - ${INFLUXDB_PORT}:${INFLUXDB_PORT}
  #   volumes:
  #     - ./services/influxdb/data:/var/lib/influxdb
  #   env_file: .env

  # influxdb-chronograf:
  #   image: chronograf:latest
  #   ports:
  #     - ${INFLUXDB_CHRONOGRAF_PORT}:${INFLUXDB_CHRONOGRAF_PORT}
  #   volumes:
  #     - ./services/influxdb-chronograf/data:/var/lib/chronograf
  #   env_file: .env

  # influxdb-telegraf:
  #   image: telegraf:latest
  #   ports:
  #     - ${INFLUXDB_TELEGRAF_STATSD_PORT}:${INFLUXDB_TELEGRAF_STATSD_PORT}
  #     - ${INFLUXDB_TELEGRAF_UDP_PORT}:${INFLUXDB_TELEGRAF_UDP_PORT}
  #     - ${INFLUXDB_TELEGRAF_TCP_PORT}:${INFLUXDB_TELEGRAF_TCP_PORT}
  #   volumes:
  #     - ./services/influxdb-telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  #   env_file: .env

  # influxdb-kapacitor:
  #   image: kapacitor:latest
  #   ports:
  #     - ${INFLUXDB_KAPACITOR_PORT}:${INFLUXDB_KAPACITOR_PORT}
  #   volumes:
  #     - ./services/influxdb-kapacitor/data:/var/lib/kapacitor
  #   env_file: .env

  # noflo:
  #   build: ./services/noflo
  #   ports:
  #     - ${NOFLO_PORT}:${NOFLO_PORT}
  #   volumes:
  #     - ./services/noflo:/service
  #   env_file: .env

  # arangodb:
  #   image: arangodb
  #   ports:
  #     - ${ARANGO_PORT}:${ARANGO_PORT}
  #   volumes:
  #     - ./services/arangodb/data:/var/lib/arangodb3
  #     - ./services/arangodb/apps:/var/lib/arangodb3-apps
  #   env_file: .env

  # rethinkdb:
  #   build: ./services/rethinkdb
  #   ports:
  #     - ${RETHINKDB_PORT}:${RETHINKDB_PORT}
  #     - ${RETHINKDB_PORT_INTRACLUSTER}:${RETHINKDB_PORT_INTRACLUSTER}
  #     - ${RETHINKDB_PORT_WEB}:${RETHINKDB_PORT_WEB}
  #   volumes:
  #     - ./services/rethinkdb/data:/data
  #   env_file: .env

  # rethinkdb-chateau:
  #   build: ./services/rethinkdb-chateau
  #   ports:
  #     - ${RETHINKDB_CHATEAU_PORT}:${RETHINKDB_CHATEAU_PORT}
  #   volumes:
  #     - ./services/rethinkdb-chateau:/service
  #   env_file: .env
