FROM node:latest

# Install packages
RUN apt-get update -y
RUN apt-get upgrade -y

# Create app directory
RUN mkdir -p /service

# Install app dependencies
COPY ./app/package.json /service/
COPY ./app/yarn.lock /service/
WORKDIR /service
RUN yarn install

# Bundle app source
COPY ./app /service/
RUN npm run build

# Set version and start
EXPOSE 3000
CMD npm start
