version: '3'
services:
  proxy:
    image: traefik
    command: '-c /dev/null --api --docker --docker.domain=tomwieland.nl --logLevel=DEBUG'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './services/proxy/traefik.toml:/traefik.toml'
      - './services/proxy/acme.json:/acme.json'

  postgresql:
    image: 'postgres:latest'
    ports:
      - '${POSTGRESQL_PORT}:${POSTGRESQL_PORT}'
    volumes:
      - './services/postgresql/data:/var/lib/postgresql/data'
    env_file: .env

  postgresql-admin:
    depends_on:
      - postgresql
    image: dpage/pgadmin4:latest
    ports:
      - '${POSTGRESQL_ADMIN_PORT}:80'
    volumes:
      - './services/postgresql-admin/data:/root/.pgadmin'
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: 'tom.wieland@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    labels:
      traefik.frontend.rule: 'Host:${PRISMA_HOST}.tomwieland.nl'
      traefik.backend: '${PRISMA_HOST}'
      traefik.port: '${PRISMA_PORT}'

  prisma:
    depends_on:
      - postgresql
    image: prismagraphql/prisma:1.22
    ports:
      - '${PRISMA_PORT}:${PRISMA_PORT}'
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_PORT}
        # uncomment the next line and provide the env var
        # PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ${POSTGRESQL_HOST}
            port: ${POSTGRESQL_PORT}
            user: ${POSTGRESQL_USER}
            password: ${POSTGRESQL_PASSWORD}
            migrations: true
            rawAccess: true
    labels:
      traefik.frontend.rule: 'Host:${PRISMA_HOST}.tomwieland.nl'
      traefik.backend: '${PRISMA_HOST}'
      traefik.port: '${PRISMA_PORT}'

  tensorflow:
    image: tensorflow/tensorflow
    ports:
      - '${TENSORFLOW_PORT}:8888'
    volumes:
      - './common/tensorflow/tf:/tf'
    env_file: .env
    command: 'bash -c "source /etc/bash.bashrc && jupyter notebook --notebook-dir=/tf --ip=${TENSORFLOW_HOST} --no-browser --allow-root"'
    labels:
      traefik.frontend.rule: 'Host:${TENSORFLOW_HOST}.tomwieland.nl'
      traefik.backend: '${TENSORFLOW_HOST}'
      traefik.port: '8888'

  tf-serve:
    image: tobegit3hub/simple_tensorflow_serving
    ports:
      - '${TF_SERVE_PORT}:8500'
    volumes:
      - './common/tensorflow/tf:/tf'
    env_file: .env
    command: 'simple_tensorflow_serving --model_base_path=/tf'
    labels:
      traefik.frontend.rule: 'Host:${TF_SERVE_HOST}.tomwieland.nl'
      traefik.backend: '${TF_SERVE_HOST}'
      traefik.port: '${TF_SERVE_PORT}'

  api:
    depends_on:
      - prisma
    build: services/api
    volumes:
      - './services/api:/service'
    env_file: .env

  web:
    depends_on:
      - prisma
    build: services/web
    ports:
      - '${WEB_PORT}:${WEB_PORT}'
      - '${WEB_HMR_PORT}:${WEB_HMR_PORT}'
    volumes:
      - './services/web:/service'
    env_file: .env
    labels:
      traefik.frontend.rule: 'Host:web.tomwieland.nl'
      traefik.backend: '${WEB_HOST}'
      traefik.port: '${WEB_PORT}'
