projects:
  app:
    schemaPath: src/datamodel.graphql
    extensions:
      endpoints:
        # TODO: Don't cardcode port here. Take from .env file.
        default: http://localhost:8020
  prisma:
    schemaPath: src/datamodel.prisma.gen.graphql
    extensions:
      prisma: prisma.yml
