projects:
  app:
    schemaPath: src/datamodel.graphql
    extensions:
      endpoints:
        default: api.docker.localhost
  prisma:
    schemaPath: src/datamodel.prisma.gen.graphql
    extensions:
      prisma: prisma.yml
